### PR TITLE
get vraylib working

### PR DESCRIPTION
**Pull request by waozixyz**
i had to remove some functions and add some typdefs, its probably not perfect, but atleast i could run it now without getting an error

### CODE REVIEW

**Comment by raysan5** [comment]
@waotzi Great work! Feel free to update [raylib BINDINGS version](https://github.com/raysan5/raylib/blob/master/BINDINGS.md) once merged!

**Comment by waozixyz** [comment]
@raysan5 thank you ray! i will do that once its merged :+1:

**Comment by spytheman** [comment]
Thank you very much !!!

**Comment by manen** [comment]
Why hasn't this been merged yet?

**Comment by manen** [comment]
Also, I'm trying out @waotzi's fork, and I'm having trouble loading textures. I'm trying to load a simple 256x128 png, and this is the output.
```
INFO: FILEIO: [assets/car.png] File loaded successfully
INFO: IMAGE: [assets/car.png] Data loaded successfully (256x128)
RUNTIME ERROR: invalid memory access
```
and it crashes.

**Comment by waozixyz** [comment]
@manen mhm are you using raylib 3.5?

**Comment by manen** [comment]
> are you using raylib 3.5?

Pretty sure I am

**Comment by waozixyz** [comment]
@manen have you tried doing the same example in c + raylib? i cant replicate the error you are getting

**Pull request closed without merging**
